import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.js',
        './app/Livewire/**/*Table.php',
        './vendor/power-components/livewire-powergrid/resources/views/**/*.php',
        './vendor/power-components/livewire-powergrid/src/Themes/Tailwind2.php'
    ],
    presets: [
        require("./vendor/power-components/livewire-powergrid/tailwind.config.js"),
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-dim": "#f1d4cf",
                "error": "#ba1a1a",
                "status-progress-bg": "#FEF3C7",
                "on-tertiary-fixed": "#000c61",
                "inverse-primary": "#ffb4a8",
                "primary-container": "#990000",
                "on-error-container": "#93000a",
                "surface-tint": "#b82014",
                "status-pending-text": "#6B7280",
                "on-surface": "#271815",
                "tertiary-container": "#0029dc",
                "progress-high": "#059669",
                "surface-container": "#ffe9e6",
                "on-secondary-fixed": "#191c1f",
                "on-tertiary-container": "#abb4ff",
                "progress-medium": "#D97706",
                "divider": "#F3F4F6",
                "on-surface-variant": "#5b403c",
                "on-secondary-fixed-variant": "#44474a",
                "surface-bright": "#fff8f6",
                "secondary": "#5c5f62",
                "primary-fixed": "#ffdad4",
                "on-background": "#271815",
                "progress-low": "#DC2626",
                "surface-container-highest": "#f9dcd7",
                "secondary-container": "#dee0e4",
                "on-error": "#ffffff",
                "inverse-surface": "#3e2c29",
                "status-overdue-bg": "#FEE2E2",
                "on-primary-fixed": "#410000",
                "secondary-fixed-dim": "#c4c7ca",
                "secondary-fixed": "#e0e2e6",
                "status-delayed-text": "#9A3412",
                "on-secondary-container": "#606366",
                "surface-container-high": "#ffe2dd",
                "on-primary": "#ffffff",
                "outline-variant": "#e4beb8",
                "on-tertiary": "#ffffff",
                "on-primary-container": "#ffa092",
                "primary": "#6e0000",
                "background": "#fff8f6",
                "status-progress-text": "#92400E",
                "on-tertiary-fixed-variant": "#0027d4",
                "surface-container-lowest": "#ffffff",
                "error-container": "#ffdad6",
                "on-primary-fixed-variant": "#930000",
                "tertiary-fixed-dim": "#bcc2ff",
                "surface-container-low": "#fff0ee",
                "inverse-on-surface": "#ffedea",
                "surface": "#fff8f6",
                "tertiary-fixed": "#dfe0ff",
                "status-pending-bg": "#E5E7EB",
                "status-completed-text": "#065F46",
                "tertiary": "#001ba0",
                "status-completed-bg": "#D1FAE5",
                "status-delayed-bg": "#FED7AA",
                "outline": "#8f706b",
                "surface-variant": "#f9dcd7",
                "status-overdue-text": "#991B1B",
                "primary-fixed-dim": "#ffb4a8",
                "on-secondary": "#ffffff"
            },
            fontFamily: {
                "label-sm": ["Inter", "sans-serif"],
                "label-md": ["Inter", "sans-serif"],
                "headline-md": ["Plus Jakarta Sans", "sans-serif"],
                "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
                "body-lg": ["Inter", "sans-serif"],
                "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
                "body-md": ["Inter", "sans-serif"],
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
            },
            spacing: {
                "container-padding": "16px",
                "component-gap": "8px",
                "bottom-nav-height": "64px",
                "top-bar-height": "56px",
                "gutter": "12px"
            },
            transitionTimingFunction: {
                'spring': 'cubic-bezier(0.32, 0.72, 0, 1)',
            },
            boxShadow: {
                'micro': '0 2px 8px rgba(0,0,0,0.04)',
                'glass': '0 8px 32px 0 rgba(153, 0, 0, 0.1)',
            }
        },
    },
    plugins: [forms],
};
